"""base_schema

Revision ID: 21bd9bbea08b
Revises: 
Create Date: 2023-03-08 14:09:06.560987

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = '21bd9bbea08b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    query = """
        CREATE TABLE `studies` (
        `id` binary(32) NOT NULL COMMENT 'guid generated by backend api',
        `name` varchar(500) NOT NULL,
        `institution` text NOT NULL,
        `created_at` datetime NOT NULL,
        unique key unique_name(name),
        PRIMARY KEY (`id`)
        )
    """
    conn.execute(text(query))
    query = """
        CREATE TABLE `datasets` (
          `id` binary(32) NOT NULL COMMENT 'generated guid',
          `name` varchar(500) NOT NULL,
          `data_source_type` varchar(10) NOT NULL,
          `data_type` varchar(10) NOT NULL,
          `genome_build` varchar(10) NOT NULL,
          `ancestry` varchar(10) NOT NULL,
          `sex` varchar(10) NOT NULL,
          `global_sample_size` int NOT NULL,
          `status` varchar(10) NOT NULL,
          `data_submitter` text NOT NULL,
          `data_submitter_email` text NOT NULL,
          `data_contributor` text,
          `data_contributor_email` text,
          `study_id` binary(32) NOT NULL,
          `description` text NOT NULL,
          `pmid` bigint DEFAULT NULL,
          `publication` text,
          `created_at` datetime NOT NULL,
          PRIMARY KEY (`id`),
          unique key unique_name(name),
          KEY `datasets_studies_id_fk` (`study_id`),
          CONSTRAINT `datasets_studies_id_fk` FOREIGN KEY (`study_id`) REFERENCES `studies` (`id`)
        )
    """
    conn.execute(text(query))
    query = """
        CREATE TABLE `dataset_phenotypes` (
            `id` binary(32) NOT NULL,
            `dataset_id` binary(32) NOT NULL,
            `phenotype` varchar(30) NOT NULL,
            `s3_path` text NOT NULL,
            `dichotomous` tinyint(1) NOT NULL,
            `sample_size` int DEFAULT NULL,
            `cases` int DEFAULT NULL,
            `controls` int DEFAULT NULL,
            `created_at` datetime NOT NULL,
            `file_name` text NOT NULL,
            PRIMARY KEY (`id`),
            KEY `dataset_phenotypes_datasets_id_fk` (`dataset_id`),
            CONSTRAINT `dataset_phenotypes_datasets_id_fk` FOREIGN KEY (`dataset_id`) REFERENCES `datasets` (`id`)
        )
    """
    conn.execute(text(query))


def downgrade() -> None:
    conn = op.get_bind()
    query = """
    DROP TABLE studies;
    """
    conn.execute(text(query))
    query = """
    DROP TABLE datasets;
    """
    conn.execute(text(query))
    query = """
    DROP TABLE dataset_phenotypes;
    """
    conn.execute(text(query))
