"""sgc_cohorts_table

Revision ID: def789ghi012
Revises: abc123def456
Create Date: 2025-02-08 15:00:00.000000

"""
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = 'def789ghi012'
down_revision = 'abc123def456'
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    
    # Create sgc_cohorts table
    query = """
        CREATE TABLE `sgc_cohorts` (
        `id` binary(32) NOT NULL COMMENT 'guid generated by backend api',
        `name` varchar(255) NOT NULL,
        `uploaded_by` varchar(255) NOT NULL,
        `total_sample_size` int NOT NULL,
        `number_of_males` int NOT NULL,
        `number_of_females` int NOT NULL,
        `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (`id`),
        UNIQUE KEY `unique_cohort_name_uploader` (`name`, `uploaded_by`)
        )
        """
    conn.execute(text(query))


def downgrade() -> None:
    conn = op.get_bind()
    conn.execute(text("DROP TABLE `sgc_cohorts`"))