"""create sgc_gwas_files table

Revision ID: create_sgc_gwas_files
Revises: add_unique_peg_name
Create Date: 2025-12-22 18:17:00.000000

"""
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = 'create_sgc_gwas_files'
down_revision = 'add_unique_peg_name'
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    
    # Create sgc_gwas_files table
    query = """
        CREATE TABLE `sgc_gwas_files` (
        `id` binary(32) NOT NULL COMMENT 'guid generated by backend api',
        `cohort_id` binary(32) NOT NULL COMMENT 'foreign key to sgc_cohorts',
        `dataset` varchar(100) NOT NULL COMMENT 'dataset name/identifier',
        `phenotype` varchar(100) NOT NULL COMMENT 'phenotype name',
        `ancestry` varchar(50) NOT NULL COMMENT 'ancestry code',
        `file_name` varchar(255) NOT NULL,
        `file_size` bigint NOT NULL COMMENT 'file size in bytes',
        `s3_path` varchar(500) NOT NULL COMMENT 's3 key path',
        `uploaded_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `uploaded_by` varchar(100) NOT NULL,
        `column_mapping` json NOT NULL COMMENT 'JSON mapping of file columns to standard GWAS fields',
        `metadata` json NULL COMMENT 'additional metadata about the GWAS file',
        PRIMARY KEY (`id`),
        KEY `sgc_gwas_files_cohort_fk` (`cohort_id`),
        KEY `sgc_gwas_files_phenotype_idx` (`phenotype`),
        KEY `sgc_gwas_files_dataset_idx` (`dataset`),
        CONSTRAINT `sgc_gwas_files_cohort_fk` FOREIGN KEY (`cohort_id`) REFERENCES `sgc_cohorts` (`id`) ON DELETE CASCADE
        )
        """
    conn.execute(text(query))


def downgrade() -> None:
    conn = op.get_bind()
    conn.execute(text("DROP TABLE `sgc_gwas_files`"))
