"""sgc_cases_controls_metadata_table

Revision ID: jkl456mno789
Revises: ghi123jkl456
Create Date: 2025-02-08 17:00:00.000000

"""
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = 'jkl456mno789'
down_revision = 'ghi123jkl456'
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    
    # Create sgc_cases_controls_metadata table
    query = """
        CREATE TABLE `sgc_cases_controls_metadata` (
        `id` binary(32) NOT NULL COMMENT 'guid generated by backend api',
        `file_id` binary(32) NOT NULL COMMENT 'foreign key to sgc_cohort_files',
        `distinct_phenotypes` json NOT NULL COMMENT 'list of distinct phenotype codes in the file',
        `total_cases` int NOT NULL COMMENT 'sum of all case counts in the file',
        `total_controls` int NOT NULL COMMENT 'sum of all control counts in the file',
        `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (`id`),
        UNIQUE KEY `unique_file_metadata` (`file_id`),
        KEY `sgc_cases_controls_metadata_file_fk` (`file_id`),
        CONSTRAINT `sgc_cases_controls_metadata_file_fk` FOREIGN KEY (`file_id`) REFERENCES `sgc_cohort_files` (`id`) ON DELETE CASCADE
        )
        """
    conn.execute(text(query))


def downgrade() -> None:
    conn = op.get_bind()
    conn.execute(text("DROP TABLE `sgc_cases_controls_metadata`"))