"""sgc_cohort_files_table

Revision ID: ghi123jkl456
Revises: def789ghi012
Create Date: 2025-02-08 16:00:00.000000

"""
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = 'ghi123jkl456'
down_revision = 'def789ghi012'
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    
    # Create sgc_cohort_files table
    query = """
        CREATE TABLE `sgc_cohort_files` (
        `id` binary(32) NOT NULL COMMENT 'guid generated by backend api',
        `cohort_id` binary(32) NOT NULL COMMENT 'foreign key to sgc_cohorts',
        `file_type` varchar(50) NOT NULL,
        `file_path` varchar(500) NOT NULL,
        `file_name` varchar(255) NOT NULL,
        `file_size` int NOT NULL,
        `uploaded_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (`id`),
        UNIQUE KEY `unique_cohort_file_type` (`cohort_id`, `file_type`),
        KEY `sgc_cohort_files_cohort_fk` (`cohort_id`),
        CONSTRAINT `sgc_cohort_files_cohort_fk` FOREIGN KEY (`cohort_id`) REFERENCES `sgc_cohorts` (`id`) ON DELETE CASCADE
        )
        """
    conn.execute(text(query))


def downgrade() -> None:
    conn = op.get_bind()
    conn.execute(text("DROP TABLE `sgc_cohort_files`"))