"""add calr public and format

Revision ID: add_calr_public_and_format
Revises: create_calr_files
Create Date: 2026-03-02 18:48:00.000000

"""
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = 'add_calr_public_and_format'
down_revision = '3ee8662aa028'
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()

    # Create calr_submissions table
    conn.execute(text("""
        CREATE TABLE `calr_submissions` (
        `id` binary(32) NOT NULL COMMENT 'guid generated by backend api',
        `name` varchar(255) NOT NULL COMMENT 'user-provided label for the submission',
        `description` text COMMENT 'user-provided description',
        `public` tinyint(1) NOT NULL DEFAULT 0,
        `uploaded_by` varchar(255) NOT NULL,
        `uploaded_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (`id`),
        KEY `idx_calr_submissions_uploaded_by` (`uploaded_by`),
        KEY `idx_calr_submissions_public` (`public`)
        )
    """))

    # Alter calr_files: add submission_id and file_type, drop name and uploaded_by
    conn.execute(text("""
        ALTER TABLE `calr_files`
            ADD COLUMN `submission_id` binary(32) NOT NULL AFTER `id`,
            ADD COLUMN `file_type` varchar(20) NOT NULL COMMENT 'standard or session' AFTER `submission_id`,
            DROP COLUMN `name`,
            DROP COLUMN `uploaded_by`,
            ADD KEY `idx_calr_files_submission_id` (`submission_id`)
    """))


def downgrade() -> None:
    conn = op.get_bind()

    conn.execute(text("""
        ALTER TABLE `calr_files`
            DROP KEY `idx_calr_files_submission_id`,
            DROP COLUMN `submission_id`,
            DROP COLUMN `file_type`,
            ADD COLUMN `name` varchar(255) NOT NULL AFTER `id`,
            ADD COLUMN `uploaded_by` varchar(255) NOT NULL AFTER `uploaded_at`
    """))

    conn.execute(text("DROP TABLE `calr_submissions`"))
