"""create sgc_gwas_cohorts table

Revision ID: create_sgc_gwas_cohorts
Revises: add_sgc_phenotypes_feb2026
Create Date: 2026-02-25 12:00:00.000000

"""
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = 'create_sgc_gwas_cohorts'
down_revision = 'add_sgc_phenotypes_feb2026'
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    conn.execute(text("""
        CREATE TABLE `sgc_gwas_cohorts` (
            `id`           binary(32)   NOT NULL COMMENT 'guid generated by backend api',
            `name`         varchar(255) NOT NULL COMMENT 'cohort name',
            `submitted_by` varchar(255) NOT NULL COMMENT 'username of submitter',
            `metadata`     json         NOT NULL COMMENT 'all cohort-level form fields',
            `created_at`   datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
            `updated_at`   datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            PRIMARY KEY (`id`),
            UNIQUE KEY `uq_sgc_gwas_cohort_name_submitter` (`name`, `submitted_by`),
            KEY `sgc_gwas_cohorts_submitted_by_idx` (`submitted_by`)
        )
    """))


def downgrade() -> None:
    conn = op.get_bind()
    conn.execute(text("DROP TABLE `sgc_gwas_cohorts`"))
