"""create sgc_gwas_validation_jobs table

Revision ID: create_sgc_gwas_validation_jobs
Revises: create_hcm_gwas_files
Create Date: 2026-03-10 20:00:00.000000

"""
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = 'create_sgc_gwas_validation_jobs'
down_revision = 'create_hcm_gwas_files'
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()

    conn.execute(text("""
        CREATE TABLE `sgc_gwas_validation_jobs` (
        `id` binary(32) NOT NULL COMMENT 'guid generated by backend api',
        `file_id` binary(32) NOT NULL COMMENT 'foreign key to sgc_gwas_files',
        `batch_job_id` varchar(100) NULL COMMENT 'AWS Batch job ID',
        `status` varchar(20) NOT NULL DEFAULT 'SUBMITTED' COMMENT 'SUBMITTED, RUNNING, COMPLETED, FAILED',
        `total_rows` int NULL,
        `errors_found` int NULL,
        `error_summary` json NULL COMMENT 'sample of validation errors from progress file',
        `progress_s3_key` varchar(500) NULL COMMENT 's3 key for the progress JSON file',
        `submitted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `completed_at` datetime NULL,
        `submitted_by` varchar(100) NOT NULL,
        PRIMARY KEY (`id`),
        KEY `sgc_gwas_validation_file_idx` (`file_id`),
        KEY `sgc_gwas_validation_status_idx` (`status`),
        CONSTRAINT `sgc_gwas_validation_file_fk` FOREIGN KEY (`file_id`) REFERENCES `sgc_gwas_files` (`id`) ON DELETE CASCADE
        )
    """))


def downgrade() -> None:
    conn = op.get_bind()
    conn.execute(text("DROP TABLE `sgc_gwas_validation_jobs`"))
