"""create calr_files table

Revision ID: create_calr_files
Revises: add_peg_accession
Create Date: 2026-01-22 10:00:00.000000

"""
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = 'create_calr_files'
down_revision = 'add_peg_accession'
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()

    # Create calr_files table
    query = """
        CREATE TABLE `calr_files` (
        `id` binary(32) NOT NULL COMMENT 'guid generated by backend api',
        `name` varchar(255) NOT NULL COMMENT 'user-provided name for the file',
        `file_name` varchar(255) NOT NULL COMMENT 'original filename',
        `file_size` bigint NOT NULL,
        `s3_path` varchar(500) NOT NULL,
        `uploaded_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `uploaded_by` varchar(255) NOT NULL,
        PRIMARY KEY (`id`),
        KEY `idx_calr_files_uploaded_by` (`uploaded_by`),
        KEY `idx_calr_files_uploaded_at` (`uploaded_at`)
        )
        """
    conn.execute(text(query))


def downgrade() -> None:
    conn = op.get_bind()
    conn.execute(text("DROP TABLE `calr_files`"))
