"""create hcm_gwas_files table

Revision ID: create_hcm_gwas_files
Revises: 273a7a8181c0
Create Date: 2026-03-10 15:00:00.000000

"""
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = 'create_hcm_gwas_files'
down_revision = '273a7a8181c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()

    conn.execute(text("""
        CREATE TABLE `hcm_gwas_files` (
        `id` binary(32) NOT NULL COMMENT 'guid generated by backend api',
        `cohort_name` varchar(255) NOT NULL COMMENT 'contributing study/cohort name',
        `sarc` varchar(10) NOT NULL COMMENT 'ALL, SP (SARC+), or SN (SARC-)',
        `ancestry` varchar(50) NOT NULL COMMENT 'EUR, AFR, EAS, SAS, AMR, or ALL',
        `sex` varchar(10) NOT NULL COMMENT 'ALL, MALE, or FEMALE',
        `genome_build` varchar(10) NOT NULL COMMENT 'GRCh37 or GRCh38',
        `software` varchar(100) NOT NULL COMMENT 'analysis software e.g. REGENIE, SAIGE',
        `analyst` varchar(100) NOT NULL COMMENT 'analyst initials',
        `file_name` varchar(255) NOT NULL,
        `file_size` bigint NOT NULL COMMENT 'file size in bytes',
        `s3_path` varchar(500) NOT NULL COMMENT 's3 key path',
        `uploaded_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `uploaded_by` varchar(100) NOT NULL,
        `column_mapping` json NOT NULL COMMENT 'JSON mapping of file columns to standard GWAS fields',
        `cases` int NULL COMMENT 'number of cases',
        `controls` int NULL COMMENT 'number of controls',
        `metadata` json NULL COMMENT 'additional metadata',
        PRIMARY KEY (`id`),
        KEY `hcm_gwas_files_cohort_idx` (`cohort_name`),
        KEY `hcm_gwas_files_ancestry_idx` (`ancestry`),
        KEY `hcm_gwas_files_sarc_idx` (`sarc`),
        KEY `hcm_gwas_files_uploaded_by_idx` (`uploaded_by`)
        )
    """))


def downgrade() -> None:
    conn = op.get_bind()
    conn.execute(text("DROP TABLE `hcm_gwas_files`"))
