name: CI

on:
  push:
    branches:
      - "main"
    tags:
      - 'V*.*.*'

  pull_request:
    branches:
      - "*"
jobs:
  test:
    name: Run tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Start MySQL
        run: |
          sh docker_db/docker_db.sh start

      - name: Show dependencies
        run: | 
          pip list

      - name: Test with pytest with coverage
        run: |
          pytest --cov=. --cov-report=xml

      - name: Stop MySQL
        run: |
          sh docker_db/docker_db.sh stop

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-coverage: ./coverage.xml


  deploy-qa:
    needs: [ test ]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Deploy to QA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          python-version: '3.8'
          deploy-environment: 'dev'
          host: ${{ secrets.DEPLOY_HOST }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}

  deploy-prod:
    needs: [ test ]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/V')
    name: Deploy to Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          python-version: '3.8'
          deploy-environment: 'prd'
          host: ${{ secrets.DEPLOY_HOST }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          tag-name: ${{ github.ref_name }}
